/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aop;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class App {

	public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}

	@Bean
	public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
		return args -> {

			ServiceOne serviceOne = ctx.getBean("ServiceOne", ServiceOne.class);
			serviceOne.add("hehehe");

			ServiceTwo serviceTwo = ctx.getBean("ServiceTwo", ServiceTwo.class);
			serviceTwo.add("hahaha");
		};
	}

}
