/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ioc;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	@Bean
	public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
		return args -> {
			// 从SpringBoot 创建的IOC容器中获取 fileWriterService 这个Bean
			FileWriterService fileWriterService = ctx.getBean("fileWriterService", FileWriterService.class);
			fileWriterService.write("hehehe");
		};
	}

}
